spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: welcome
    url: jdbc:mysql://localhost/infytel_calldetails
  jpa:
    hibernate:
      ddl-auto: update
