spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: welcome
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
      service-url:
          defaultZone: http://peer1:2222/eureka,http://peer2:3333/eureka
